---
name: Daily monitoring for platform operations
trigger:
  - master
pr:
  - master
schedules:
  - cron: '0 9 * * Mon-Fri'
    displayName: Runs 9 AM Mon-Fri
    branches:
      include:
        - master
    always: 'true'

parameters:

  - name: ado_pipelines
    type: object
    default:
      - project: 'cnp'
        definitionId: '37'
        timeForAmber: '3 days'
        timeForRed: '5 days'
        pipelineName: "Preview PR cleanup"
      - project: 'cnp'
        definitionId: '276'
        timeForAmber: '3 days'
        timeForRed: '7 days'
        pipelineName: "ACR hmctspublic Cleanup"
      - project: 'PlatformOperations'
        definitionId: '449'
        timeForAmber: '7 days'
        timeForRed: '14 days'
        pipelineName: "Github offboarding"
      - project: 'PlatformOperations'
        definitionId: '460'
        timeForAmber: '3 days'
        timeForRed: '7 days'
        pipelineName: "Github offboarding reconciliation"
      - project: 'cnp'
        definitionId: '463'
        timeForAmber: '14 days'
        timeForRed: '28 days'
        pipelineName: "Launch Darkly cleanup"
      - project: 'PlatformOperations'
        definitionId: '472'
        timeForAmber: '3 days'
        timeForRed: '7 days'
        pipelineName: "Azure AAD group cleanup"
      - project: 'cnp'
        definitionId: '545'
        timeForAmber: '3 days'
        timeForRed: '7 days'
        pipelineName: "OWASP DB update"
      - project: 'cnp'
        definitionId: '175'
        timeForAmber: '3 days'
        timeForRed: '7 days'
        pipelineName: "ACR Base importer"
      - project: 'Platform%20Engineering'
        definitionId: '224'
        timeForAmber: '3 days'
        timeForRed: '5 days'
        pipelineName: "Preview scheduled cleanup"
  - name: aks_clusters
    type: object
    default:
      - resourceGroup: 'cft-preview-00-rg'
        clusterName: 'cft-preview-00-aks'
        subscription: 'DCD-CFTAPPS-DEV'
      - resourceGroup: 'cft-preview-01-rg'
        clusterName: 'cft-preview-01-aks'
        subscription: 'DCD-CFTAPPS-DEV'
jobs:
  - job: DailyMonitoring
    timeoutInMinutes: 10
    pool:
      name: 'hmcts-cftptl-agent-pool'
    steps:
      - task: AzureKeyVault@1
        displayName: 'Get secrets from Keyvault'
        inputs:
          azureSubscription:  "DTS-CFTPTL-INTSVC"
          keyVaultName:   "cftptl-intsvc"
          secretsFilter: 'slack-webhook-url,azure-devops-token,jira-password,jira-username,github-management-api-token'
      - task: Bash@3
        displayName: 'Create a slack message file'
        inputs:
          targetType: 'inline'
          script: |
           echo "*Daily Monitoring summary* \n \n">> slack-message.txt
           echo "_:azure: *Scheduled Pipelines status*_ \n">> slack-message.txt
      - ${{ each ado_pipeline in parameters.ado_pipelines }}:
        - task: Bash@3
          displayName: 'Checking azure pipeline status ${{ado_pipeline.pipelineName}}'
          inputs:
            targetType: filePath
            filePath: scripts/ado-pipeline-monitor.sh
            arguments: $(azure-devops-token) ${{ado_pipeline.project}} ${{ado_pipeline.definitionId}}  "${{ado_pipeline.timeForAmber}}"  "${{ado_pipeline.timeForRed}}"  "${{ado_pipeline.pipelineName}}"
      - task: Bash@3
        displayName: 'Checking Github Licenses'
        inputs:
          targetType: filePath
          filePath: scripts/github-licenses.sh
          arguments: $(github-management-api-token)
      - ${{ each cluster in parameters.aks_clusters }}:
        - task: AzureCLI@2
          displayName: 'Get AKS Cluster Status'
          inputs:
            scriptType: bash
            scriptPath: scripts/aks-node-count.sh
            azureSubscription: ${{ cluster.subscription }}
            arguments: ${{cluster.resourceGroup}} ${{cluster.clusterName}}
      - task: Bash@3
        displayName: 'Checking JIRA status'
        inputs:
          targetType: filePath
          filePath: scripts/jira-status.sh
          arguments: $(jira-username) $(jira-password)
      - task: Bash@3
        displayName: 'Send slack message'
        inputs:
          targetType: filePath
          filePath: scripts/send-slack-message.sh
          arguments: $(slack-webhook-url) dtspo-daily-monitoring-test