---
name: Daily monitoring for platform operations
trigger:
  - master
pr:
  - master
schedules:
  - cron: '0 9 * * Mon-Fri'
    displayName: Runs 9 AM Mon-Fri
    branches:
      include:
        - master
    always: 'true'

parameters:

  - name: ado_pipelines
    type: object
    default:
      - project: 'cnp'
        definitionId: '37'
        hoursForAmber: '24'
        hoursForRed: '48'
        pipelineName: "Preview PR cleanup"

      - project: 'cnp'
        definitionId: '276'
        hoursForAmber: '24'
        hoursForRed: '72'
        pipelineName: "ACR hmctspublic Cleanup"
jobs:
  - job: dailychecks
    timeoutInMinutes: 10
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: AzureKeyVault@1
        displayName: 'Get webhook from Keyvault'
        inputs:
          azureSubscription:  "DTS-CFTPTL-INTSVC"
          keyVaultName:   "cftptl-intsvc"
          secretsFilter: 'slack-webhook-url,azure-devops-token'
      - task: Bash@3
        displayName: 'Create a slack message file'
        inputs:
          targetType: 'inline'
          script: touch slack-message.txt >> slack-message.txt
      - ${{ each ado_pipeline in parameters.ado_pipelines }}:
        - task: Bash@3
          displayName: 'Checking azure pipeline status'
          inputs:
            targetType: filePath
            filePath: scripts/ado-pipeline-monitor.sh
            arguments: $(azure-devops-token) ${{ado_pipeline.project}} ${{ado_pipeline.definitionId}}  ${{ado_pipeline.hoursForAmber}}  ${{ado_pipeline.hoursForRed}}  ${{ado_pipeline.pipelineName}}

      - task: Bash@3
        displayName: 'Send slack message'
        inputs:
          targetType: filePath
          filePath: scripts/send-slack-message.sh
          arguments: $(slack-webhook-url) dtspo-daily-monitoring-test