---
name: Daily monitoring for platform operations
trigger:
  - master
pr:
  - master
schedules:
  - cron: '0 9 * * Mon-Fri'
    displayName: Runs 9 AM Mon-Fri
    branches:
      include:
        - master
    always: 'true'

jobs:
  - job: Daily Monitoring tasks
    timeoutInMinutes: 10
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: templates/pipeline-monitoring.yml