---
name: Daily monitoring for platform operations
trigger: none
pr:
  - master

variables:
- group: daily-checks-ghapp

jobs:
  - job: DailyMonitoring
    timeoutInMinutes: 20
    steps:
      - task: DownloadSecureFile@1
        name: pemFile
        inputs:
          secureFile: 'hmcts-daily-checks-private-key.pem'

      # Create JWT
      - task: Bash@3
        displayName: 'create GHApps access token (JWT) from private key'
        inputs:
          targetType: filePath
          filePath: scripts/create-github-app-jwt.sh
          arguments: $(appID) $(pemFile.secureFilePath) 

      - task: Bash@3
        displayName: 'display jwt'
        inputs:
          targetType: inline
          script: |
            echo $(jwt)

      - task: Bash@3
        displayName: 'test jwt'
        inputs:
          targetType: inline
          script: |
            TestUrl="https://api.github.com/app"
            gh_accesstoken=$(jwt)

            # Define headers
            AcceptHeader="application/vnd.github+json"
            AuthorizationHeader="Bearer $gh_accesstoken"
            testResponse=$(curl -s -H "Accept: $AcceptHeader" -H "Authorization: $AuthorizationHeader" "$TestUrl")

            echo "$testResponse" | jq
