---
name: Daily monitoring for platform operations
trigger:
  - master
pr:
  - master
schedules:
  - cron: '0 9 * * Mon-Fri'
    displayName: Runs 9 AM Mon-Fri
    branches:
      include:
        - master
    always: 'true'

jobs:
  - job: dailychecks
    timeoutInMinutes: 10
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: AzureKeyVault@1
        displayName: 'Get webhook from Keyvault'
        inputs:
          azureSubscription:  "DTS-CFTPTL-INTSVC"
          keyVaultName:   "cftptl-intsvc"
          secretsFilter: 'slack-webhook-url,azure-devops-token'
      - task: Bash@3
        displayName: 'Create a slack message file'
        inputs:
          targetType: 'inline'
          script: touch slack-message.txt >> slack-message.txt
      - task: Bash@3
        displayName: 'Checking azure pipeline status'
        inputs:
          targetType: filePath
          filePath: scripts/ado-pipeline-monitor.sh
          arguments: $(azure-devops-token) cnp 37 24 48 "Preview PR cleanup pipeline"
      - task: Bash@3
        displayName: 'Send slack message'
        inputs:
          targetType: filePath
          filePath: scripts/send-slack-message.sh
          arguments: $(slack-webhook-url) dtspo-daily-monitoring-test